diff -r 8aeaf357dc96 spnav/__init__.py
--- a/spnav/__init__.py	Sat Feb 04 22:16:40 2012 -0500
+++ b/spnav/__init__.py	Sat Aug 24 16:36:27 2013 +0200
@@ -4,8 +4,8 @@
     Structure, Union, pythonapi
 
 # OMG CALLING CPYTHON FUNCTIONS FROM INSIDE PYTHON
-pythonapi.PyCObject_AsVoidPtr.restype = c_void_p
-pythonapi.PyCObject_AsVoidPtr.argtypes = [py_object]
+pythonapi.PyCapsule_GetPointer.restype = c_void_p
+pythonapi.PyCapsule_GetPointer.argtypes = [py_object]
 
 import os
 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
@@ -215,7 +215,7 @@
       Raises ``SpnavConnectionException`` if Space Navigator daemon
       cannot be contacted.
     '''
-    display_ptr = pythonapi.PyCObject_AsVoidPtr(display)
+    display_ptr = pythonapi.PyCapsule_GetPointer(display)
     if libspnav.spnav_x11_open(display_ptr, window) == -1:
         raise SpnavConnectionException(
             'failed to connect to the space navigator daemon')
diff -r 8aeaf357dc96 spnav/__main__.py
--- a/spnav/__main__.py	Sat Feb 04 22:16:40 2012 -0500
+++ b/spnav/__main__.py	Sat Aug 24 16:36:27 2013 +0200
@@ -6,9 +6,9 @@
         while True:
             event = spnav_poll_event()
             if event is not None:
-                print event
+                print(event)
     except KeyboardInterrupt:
-        print '\nQuitting...'
+        print('\nQuitting...')
     finally:
         spnav_close()
 
